### ISSUE TITLE
Can't seem to resize, move or see Grid on main window

### ISSUE THREAD

**Issue by mjs513** [Lecerof/TelemetryViewer#4]
Hi Lecerof,
Nice clean up on the scroll bars.  A lot simpler than my version!

Anyway been playing around with the new interface that you put together - nice by the way.  But a couple of questions:
1.  After I load a config file I see the chart windows no problem but when I left click on a chart to resize it nothing happens - can't seem to get it to work.  Same thing happens for move.
2. On the main panel I don't see the gray shaded blocks anymore.  Was a nice feature to know where you were on the grid.  They do show up when I click in the window to create a new chart though.
3.  I saw on the View -> Grid but if I click on it nothing happens.
4.  Also can't seem to find where I set grid layout, i.e., 15x8.  Is now just dependent on default chart size and size of window?

Thanks for you time
Mike

**Comment by Lecerof** [comment]
Hi, i know it is a work in progress with the resize and move. Right now they are just empty menu options that does nothing.
I have removed the grid on purpose to increase the ability to choose sizes. Now the grid will adapt to the size of your window with a standard size of 50 pixels or so per block. That is if you go fullscreen, more blocks will be introduced. Because of this the grid options also is disabled.
Since the grid is adaptive, you cant change the layout. You can however change the standard size of the chart you create when you klick once on the screen. I should add some instructions, i know. You can open it as an issue if you like :)

**Comment by mjs513** [comment]
> Now the grid will adapt to the size of your window with a standard size of 50 pixels or so per block

That's a nice feature, but would be nice to say have a option just to draw a grid so the user can see roughly the layout.  Just talking about lines not graying the boxes out but maybe like a layout view. To be honest that's what I thought the grid options was going to show.

>work in progress with the resize and move.

Got it.  Think resize is more important than move :)  If you want I can open an issue one for each.

**Comment by Lecerof** [comment]
Sure, i can implement a grid that you can hide if you like as soon as possible. Ill throw in the hide options in the view menu. But open an issue for each feature you want and each bug you find and i will be able to not forget and prioritize them depending on how hard they are to implement

**Comment by Lecerof** [comment]
Is this something that you had in mind with the grid? Its still a work in progress, need to redo the indexing. Apparently openGL indexes from the bottom left corner i think.

**Comment by mjs513** [comment]
Sorry for not getting back to you sooner got distracted on two other projects.  Anyway, what I had in mind was basically a graph paper like display, nothing fancy where boxes line up, guess you would call them reference lines.

**Comment by Lecerof** [comment]
Pull down the latest and tell what you think :)
Sure, wont have time to fix them this month though

**Comment by mjs513** [comment]
Going to close this.
